source ~/.vim/MetaBarj0.vim/basic.vim
source ~/.vim/MetaBarj0.vim/vundle_configuration.vim
source ~/.vim/MetaBarj0.vim/ycm_configuration.vim
source ~/.vim/MetaBarj0.vim/NERDTree_configuration.vim
source ~/.vim/MetaBarj0.vim/functions.vim
source ~/.vim/MetaBarj0.vim/c++_dev.vim
source ~/.vim/MetaBarj0.vim/js_dev.vim
source ~/.vim/MetaBarj0.vim/w0rpale_configuration.vim
source ~/.vim/MetaBarj0.vim/airline_configuration.vim
